In [85]:
import numpy as np
import scipy as sp
import re
from scipy.spatial import distance

In [86]:
# Запись каждого предложения в список (с понижением регистра и с отрезанием конца строки)
data_list = []
with open('sentences.txt') as file_obj:
    for line in file_obj.readlines():
        data_list.append(line.lower().strip())
print(data_list)

['in comparison to dogs, cats have not undergone major changes during the domestication process.', 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.', 'a common interactive use of cat for a single file is to output the content of a file to standard output.', 'cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.', 'in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.', 'the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.', 'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).', 'however, if the output is piped or redirected, cat is unnecessary.', 'cat with one named file is safer where human error is a conc

In [35]:
# Запись каждого предложения в список (без понижения регистра и без отрезаниz конца строки)
with open('sentences.txt') as file_obj:
    data_list2 = file_obj.readlines()
       
#print(data_list2)

## Запись содержимого файла в строку с понижением регистра и отрезанием окончания

In [89]:
a=''
with open('sentences.txt') as file_obj:
    for line in file_obj.readlines():
        a += line.lower().strip()
        
# Разрезание строки на слова и запись все в список:       
data_list3 = re.split('[^a-z]', a)

# Создание нового списка с "выкидыванием" пробелов:
data_list4 = [value for value in data_list3 if value]
print(data_list4)
print(len(data_list4))

['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', 'as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', 'a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', 'cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', 'in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', 'the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 'that',

In [90]:
# Убираем повторяющиеся слова с помощью превращения в set и обратно в list
data_set = list(set(data_list4))
print(len(data_set), data_set[1])

254 just


In [91]:
#Создаем словарь ключ - цифра от нуля до кол-ва слов в data_set, значение - слово
j = 0
dict_data_words = {}
for i in data_set:
    dict_data_words[j] = i
    j +=1
print(dict_data_words)
        

{0: 'concern', 1: 'just', 2: 'rather', 3: 'chromosomes', 4: 'separate', 5: 'lines', 6: 'the', 7: 'stdin', 8: 'most', 9: 'any', 10: 'enhancements', 11: 'domesticated', 12: 'major', 13: 'output', 14: 'processors', 15: 'clear', 16: 'using', 17: 'read', 18: 'streams', 19: 'external', 20: 'apple', 21: 'type', 22: 'tiger', 23: 'content', 24: 'be', 25: 'high', 26: 'received', 27: 'more', 28: 'running', 29: 'wrong', 30: 'linux', 31: 'released', 32: 'stdout', 33: 'non', 34: 'contains', 35: 'interactive', 36: 'safer', 37: 'have', 38: 'release', 39: 'people', 40: 'genes', 41: 'longer', 42: 'receives', 43: 'both', 44: 'files', 45: 'information', 46: 'allow', 47: 'needing', 48: 'installation', 49: 'single', 50: 'time', 51: 'displays', 52: 'adjacent', 53: 'small', 54: 'right', 55: 'permanently', 56: 'sounds', 57: 'piped', 58: 'domestic', 59: 'without', 60: 'bytes', 61: 'weighing', 62: 'installed', 63: 'by', 64: 'off', 65: 'vermin', 66: 'no', 67: 'switch', 68: 'diploid', 69: 'kg', 70: 'often', 71: 'e

In [92]:
# Создаем нулевую матрицу (кол-во предложений, кол-во слов)
matrix_cats = np.zeros((len(data_list), len(data_set)))
print(matrix_cats.shape)
print(matrix_cats)

(22, 254)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [93]:
# Создаем словарь слов в предложении
j = 0
dict_stroki = {}
for i in data_list:
    dict_stroki[j] = re.split('[^a-z]', i)
    j += 1
print(dict_stroki)



{0: ['in', 'comparison', 'to', 'dogs', '', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', ''], 1: ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', '', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', '', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', ''], 2: ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', ''], 3: ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', '', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', ''], 4: ['in', 'one', '', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', '', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', ''], 5: ['the', 'domesticated', 'cat', 'and', 'its', 'clo

In [94]:
# Заполняем матрицу кол-вом слов, входящих в предложение
for i in range(len(data_list)):
    for j in range(len(data_set)):
        m = 0
        m = dict_stroki[i].count(dict_data_words[j])
        matrix_cats[i,j] = m
print(matrix_cats[8])

[1. 1. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 2. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 1. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 2. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [104]:
# Записываем косинусные расстояния в список
ans=[]
for i in range(1, len(data_list)):
    ans.append(distance.cosine(matrix_cats[i], matrix_cats[0]))
print(ans, len(ans), sep = '\n')

[0.9527544408738466, 0.8644738145642124, 0.8951715163278082, 0.7770887149698589, 0.9402385695332803, 0.7327387580875756, 0.9258750683338899, 0.8842724875284311, 0.9055088817476932, 0.8328165362273942, 0.8804771390665607, 0.8396432548525454, 0.8703592552895671, 0.8740118423302576, 0.9442721787424647, 0.8406361854220809, 0.956644501523794, 0.9442721787424647, 0.8885443574849294, 0.8427572744917122, 0.8250364469440588]
21


In [105]:
# Выбираем 2 минимальных значения из списка ans

ans_2 = sorted(ans)
print(ans_2)

[0.7327387580875756, 0.7770887149698589, 0.8250364469440588, 0.8328165362273942, 0.8396432548525454, 0.8406361854220809, 0.8427572744917122, 0.8644738145642124, 0.8703592552895671, 0.8740118423302576, 0.8804771390665607, 0.8842724875284311, 0.8885443574849294, 0.8951715163278082, 0.9055088817476932, 0.9258750683338899, 0.9402385695332803, 0.9442721787424647, 0.9442721787424647, 0.9527544408738466, 0.956644501523794]


In [107]:
# находим порядковый номер минимальных значений

final_answer = []

for i in range(len(ans)):
    if ans[i] == ans_2[0]:
        final_answer.append(i+1)
    if ans[i] == ans_2[1]:
        final_answer.append(i+1)

print(final_answer)        

[4, 6]


In [108]:
# Записываем ответ в файл
with open('answer_C1W2_1.txt', 'w') as file_obj:
    file_obj.write(str(str(final_answer[1]) + ' ' + str(final_answer[0])))